package kz.timshowtime.accountsservice.contract;

import io.restassured.module.mockmvc.RestAssuredMockMvc;
import kz.timshowtime.accountsservice.AccountsServiceApplication;
import kz.timshowtime.accountsservice.config.TestNoSecurityConfig;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.AutoConfigureDataJpa;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.cloud.contract.verifier.messaging.boot.AutoConfigureMessageVerifier;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

@SpringBootTest(
        classes = {AccountsServiceApplication.class, TestNoSecurityConfig.class},
        webEnvironment = SpringBootTest.WebEnvironment.MOCK
)
@AutoConfigureMockMvc
@ActiveProfiles("test")
@TestPropertySource(properties = {
        "spring.liquibase.enabled=false",
        "spring.jpa.hibernate.ddl-auto=create-drop"
})
public abstract class BaseContractTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private DataSource dataSource;

    @BeforeEach
    void setup() throws SQLException {
        RestAssuredMockMvc.mockMvc(mockMvc);

        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE IF EXISTS account");

            stmt.execute("""
            CREATE TABLE IF NOT EXISTS account (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                login VARCHAR(255),
                password VARCHAR(255),
                first_name VARCHAR(255),
                last_name VARCHAR(255),
                email VARCHAR(255),
                birth_date DATE,
                balance DECIMAL(19,2),
                created_at DATE DEFAULT CURRENT_TIMESTAMP
            );
        """);

            stmt.execute("""
            INSERT INTO account (login, password, first_name, last_name, email, birth_date, balance)
            VALUES ('tim', '123456', 'Timur', 'Sultanov', 'timur@example.com', '1999-08-13', 1000.00);
        """);
        }
    }

}